# Generated by Django 2.2 on 2019-05-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190501_1208'),
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de apertura')),
                ('time', models.TimeField(verbose_name='Hora de apertura')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Apertura de puerta',
                'verbose_name_plural': 'Aperturas de puertas',
            },
        ),
        migrations.DeleteModel(
            name='Opening',
        ),
    ]
