# Generated by Django 2.2 on 2019-05-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190501_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card_rfid',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_rfid', models.CharField(default=0, max_length=10, verbose_name='Código de tarjeta RFID')),
                ('id_card', models.CharField(max_length=10, verbose_name='Cédula')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
