# Generated by Django 2.2 on 2019-05-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_entity'),
        ('users', '0003_auto_20190501_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entities',
            field=models.ManyToManyField(to='configurations.Entity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
