# Generated by Django 2.2 on 2019-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190501_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entities',
            field=models.ManyToManyField(to='configurations.Entity', verbose_name='Empresas'),
        ),
    ]
