# Generated by Django 2.2 on 2019-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=60, verbose_name='Nombre del sitio')),
                ('site_image', models.ImageField(upload_to='configuracion/general/', verbose_name='Logo')),
                ('with_image', models.PositiveIntegerField(default=100, verbose_name='Ancho del logo')),
                ('height_image', models.PositiveIntegerField(default=60, verbose_name='Alto del logo')),
            ],
        ),
    ]
