# Generated by Django 2.2 on 2019-05-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=60, verbose_name='Nombre de la entidad')),
                ('entity_image', models.ImageField(upload_to='configuracion/entity/', verbose_name='Logo')),
            ],
        ),
    ]
